#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

#TODO remove -q flag after this issue is reolve: https://github.com/okonet/lint-staged/issues/1164
echo 'running pre-commiting checks...'
npx lint-staged -q
