name: Main Workflow

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
      postgres:
        image: postgres:10
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432/tcp
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: pnpm install, build, and test
        env:
          NODE_ENV: test
          HOST: 'localhost'
          PORT: 3000
          APP_URL: 'http://localhost:4000'

          DATABASE_HOST: localhost
          DATABASE_PORT: ${{job.services.postgres.ports[5432]}}
          DATABASE_USER: postgres
          DATABASE_PASSWORD: postgres
          DATABASE_NAME: postgres
          REDIS_HOST: localhost
          REDIS_PORT: 6379

          JWT_AUTH_SECRET: 'this!is$a&hard(secret)'
          JWT_AUTH_EXPIRES_IN: '10m'

          JWT_GENERAL_SECRET: 'this!is$a&hard(secret)2'
          JWT_GENERAL_EXPIRES_IN: '10m'

          LOG_LEVEL: info

          MAILGUN_API_KEY: ''
          MAILGUN_DOMAIN: ''

        run: |
          pnpm install
          npm run test
